### ISSUE TITLE
py-rattler v0.22 breaks newest smithy v3.54.2

### ISSUE THREAD

**Issue by h-vetinari** [conda/rattler#2023]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

conda-smithy v3.54.2 was just released, which includes https://github.com/conda-forge/conda-smithy/pull/2451. That PR is a very welcome improvement, however, py-rattler v0.22 breaks the implementation of that PR

```
$ conda smithy rerender -c auto
Traceback (most recent call last):
  File "/home/[...]/miniforge/envs/builder/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/site-packages/conda_smithy/cli.py", line 748, in main
    args.subcommand_func(args)
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/site-packages/conda_smithy/cli.py", line 596, in __call__
    self._call(args, tmpdir)
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/site-packages/conda_smithy/cli.py", line 601, in _call
    configure_feedstock.main(
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/site-packages/conda_smithy/configure_feedstock.py", line 2911, in main
    check_version_uptodate("conda-smithy", __version__, True)
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/site-packages/conda_smithy/configure_feedstock.py", line 2613, in check_version_uptodate
    most_recent_version = get_most_recent_version(name).version
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/site-packages/conda_smithy/configure_feedstock.py", line 2607, in get_most_recent_version
    pkgs = asyncio.run(query())
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/[...]/miniforge/envs/builder/lib/python3.12/site-packages/conda_smithy/configure_feedstock.py", line 2599, in query
    *await gateway.query(
           ^^^^^^^^^^^^^^
TypeError: Gateway.query() got an unexpected keyword argument 'channels'
```

It works fine with v0.21

**Comment by baszalmstra** [comment]
`channels` was renamed to `sources`. I generally recommend adding an upperbound to py-rattler especially with its api still being in flux!

**Comment by h-vetinari** [comment]
Now that we start depending on this for core infrastructure (smithy etc.), could you at least give some advance warning? The tags in this repo are very noisy, and even if I subscribed, https://github.com/conda/rattler/releases/tag/py-rattler-v0.22.0 contains no information about API changes.

Version bounds have a way of hanging around until something goes boom. Perhaps we can find a middle ground that still gives you the flexibility you need to evolve, but without gratuitous breakage in conda-forge.

**Comment by baszalmstra** [comment]
That makes sense! Through which channel would you like to receive these updates?

Ill start adding a seperate CHANGELOG.md to py-rattler. I can probably also attach that to a github release.

In general though we (try) to follow relatively strict semver for all of rattlers crates and bindings. Would it be possible to automate updates in conda-smithy with something like dependabot or renovate? I think both support environment.yml.

**Comment by jaimergp** [comment]
I can't find much documentation for Dependabot's conda support, I guess this should work:

```
  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      conda:
        patterns:
          - '*'
```

But sounds like a big hammer that may update many things in the environment.yml file.

---

For API changes like this, you may take a look at how `conda` has handled this using the [`deprecations.py` module](https://github.com/conda/conda/blob/main/conda/deprecations.py). For example, this API change could have been handled like [this](https://github.com/conda/conda/blob/211ea66050120840e3c4ae2c86c277ea5ed8b697/conda/core/prefix_data.py#L129-L136):

```python
from deprecation import deprecated

    ...
	@deprecated.argument("0.22", "0.23", "channels", rename="sources")
    async def query(
        self,
        sources: Iterable[Union[Channel, str, RepoDataSource]],
        platforms: Iterable[Platform | PlatformLiteral],
        specs: Iterable[MatchSpec | PackageName | str],
        recursive: bool = True,
    ) -> List[List[RepoDataRecord]]:
      ...
```

**Comment by baszalmstra** [comment]
Thanks! Ill use that going forward!

**Comment by h-vetinari** [comment]
OK, this issue has served it's purpose. Thanks everyone!
